(require 'org-install)
(setq org-agenda-files '("~/main.org", "~/others.org"))
(define-key global-map "\C-cl" 'org-store-link)
(define-key global-map "\C-ca" 'org-agenda)
(setq org-log-done 'time)
(require 'org-habit)